version: '3'

services:
  base:
    build: .
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
    working_dir: /app

  train:
    extends:
      service: base
    command: python utils/train.py

  eval:
    extends:
      service: base
    command: python utils/eval.py

  infer:
    extends:
      service: base
    command: python utils/infer.py

  tensorboard:
    image: tensorflow/tensorflow:latest
    volumes:
      - ./logs:/logs
    ports:
      - "6006:6006"
    command: tensorboard --logdir /logs --host 0.0.0.0

  jupyter:
    extends:
      service: base
    ports:
      - "8888:8888"
    command: jupyter notebook --ip 0.0.0.0 --no-browser --allow-root
