version: '3'
services:
  train:
    build:
      context: .
    command: python train/train.py
    volumes:
      - ./data:/data
      - ./model:/app/model
  eval:
    build:
      context: .
    command: python eval/eval.py
    volumes:
      - ./data:/data
      - ./model:/app/model
  infer:
    build:
      context: .
    command: python infer/infer.py
    volumes:
      - ./data:/data
      - ./model:/app/model
