services:
    train:
        build:
            context: model-train
            dockerfile: Dockerfile.train
        volumes:
            - ./model:/workspace/model
            - ./data:/workspace/data

    evaluate:
        build:
            context: model-eval
            dockerfile: Dockerfile.eval
        volumes:
            - ./model:/workspace/model
            - ./data:/workspace/data

    server:
        build:
            context: model-deploy
            dockerfile: Dockerfile.serve
        volumes:
            - ./model:/app/model
        ports:
            - "8000:8000"
        restart: unless-stopped

    infer:
        build:
            context: model-inference
            dockerfile: Dockerfile.infer
        volumes:
            - ./data:/workspace/data
            - ./responses:/workspace/responses
        network_mode: "host"
        restart: no
