version: '3.8'

services:
  server:
    image: mnist-fastapi-compose-infer
    volumes:
      - ../model:/app/model
    ports:
      - "8000:80"
    deploy:
      replicas: 4
      restart_policy:
        condition: any
