version: '3.8'

services:
  server:
    image: mnist-fastapi-compose-server
    volumes:
      - ../model:/app/model
    ports:
      - "8000:80"
    networks:
      - app
    deploy:
      replicas: 4
      restart_policy:
        condition: on-failure

networks:
  app:
    driver: overlay
