defaults:
  - _self_
  - data: dogs
  - model: mdogs
  - paths: default

ckpt_path: ${paths.output_dir}/checkpoints/*.ckpt # null  # Path to the checkpoint file for inference
input_path: ${paths.data_dir}/validation/ # null  # Path to input data for inference
output_path: ${hydra:runtime.cwd}/validation_results/ # ${paths.output_dir}/validation_results/ # null  # Path to save inference results